// <auto-generated />
using System;

namespace Sider {
  public partial class RedisSettings {
    public string Host { get; internal set; }
    public int Port { get; internal set; }

    public RedisSettings() {
      Host = "localhost";
      Port = 6379;
    }

    public RedisSettings Clone() {
      return new RedisSettings()
      {
        Host = Host,
        Port = Port,
      };
    }

    public override int GetHashCode() {
      int hash = 17;
      hash = hash * 23 + Host.GetHashCode();
      hash = hash * 23 + Port.GetHashCode();

      return hash;
    }

    public override bool Equals(object obj) {
      if (obj == null) return false;

      var settings = obj as RedisSettings;
      if (settings == null) return false;

      var eq = true;
      eq = eq && object.Equals(Host, settings.Host);
      eq = eq && object.Equals(Port, settings.Port);

      return eq;
    }

    public partial class Builder {
      RedisSettings _settings = new RedisSettings();

      public Builder Host(string value) {
        _settings.Host = value;
        return this;
      }

      public Builder Port(int value) {
        _settings.Port = value;
        return this;
      }

      public RedisSettings Build() {
        var built = _settings;
        _settings = new RedisSettings();

        return built;
      }
    }
  }
}

